import { execSync } from 'child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const cacheDir = path.join(root, '.cache')
const cssPath = path.join(cacheDir, 'app.css')
const outputPath = path.join(root, 'lib', 'compiled-styles.ts')

mkdirSync(cacheDir, { recursive: true })

execSync(`npx sass "${path.join(root, 'styles', 'app.scss')}" "${cssPath}" --style=compressed --no-source-map`, {
  cwd: root,
  stdio: 'inherit',
})

const css = readFileSync(cssPath, 'utf8')

writeFileSync(
  outputPath,
  `// Generated by scripts/compile-styles.mjs — do not edit manually\nexport const compiledStyles = ${JSON.stringify(css)}\n`,
)

console.log(`Compiled ${css.length} bytes of CSS to lib/compiled-styles.ts`)
